### ISSUE TITLE
Re-add "seed" parameter

### ISSUE THREAD

**Issue by fabiankessler** [optimaize/language-detector#14]
I had removed the seed parameter recently because I did not understand its use.
Re-add named "consistent-results" or so.

This needs to go into the LanguageDetector, and the CommandLineInterface is affected too. See git history.

**Comment by danielnaber** [comment]
Is there a plan to have a new release with this issue fixed anytime soon? We rely on language-detector and we're running into problems if this isn't fixed (our next release is planned for end of March).

**Comment by fabiankessler** [comment]
We're just looking at this right now, and came up with a suggestion.
We believe that everyone wants consistent results. And not everyone needs to learn what a seed is. 

Current situation: a non-seeded randomizer is used, resulting in inconsistent results.

Suggested solution: 
- by default a hardcoded fixed seed is used, resulting in consistent results. 
- feature to add the seed with ´-s myseed´ (as it originally was). A user can then feed it his own seed, or call it multiple times with different seeds.

If one would still want to have the behavior as it is as of now, he'd have to pass in a randomized seed.

**Comment by fabiankessler** [comment]
It was implemented as described on 2015-01-30. No feedback was given, I'm closing this task.
This change makes it into the 0.5 release.
