### ISSUE TITLE
Profile for Khmer

### ISSUE THREAD

**Issue by danielnaber** [optimaize/language-detector#19]
I've created a profile for Khmer: http://danielnaber.de/tmp/km.zip. Here's what I did:

* exported 72,000 sentences (14MB) from Wikipedia dump
* remove sentences with traditional ASCII chars: `egrep -v "[a-zA-Z]+"` => 37,000 sentences, 9MB
* created the profile with a minimum frequency of 20

**Comment by danielnaber** [comment]
ZIP file updated to contain training data, minimum frequency increased to 50 to make the profile smaller.

**Comment by fabiankessler** [comment]
Thanks!
