### ISSUE TITLE
unclear License

### ISSUE THREAD

**Issue by danielnaber** [optimaize/language-detector#20]
`src/main/java/overview.html` still refers to the Apache License, while the README now refers to LGPLv3.

Also, did the original authors agree to the license change?

**Comment by fabiankessler** [comment]
You are right. I have just reverted the license change.

I had changed the license in several projects at that time. The others were all started from scratch. I completely forgot that I can't just do that here. Thanks for pointing it out!

**Comment by danielnaber** [comment]
Thanks. There's still one place in README.md that says "LGPLv3 (business friendly, must publish changes)".

**Comment by danielnaber** [comment]
Also, there's a `licenses` section in the pom.xml with LGPL.

**Comment by fabiankessler** [comment]
I run a fulltext search this time, and besides the reference to my invalid license change, there is no more LGPL occurring now.
