### ISSUE TITLE
README outdated

### ISSUE THREAD

**Issue by KonradHoeffner** [optimaize/language-detector#28]
- readAll() is deprecated -> change to readAllBuiltIn()
- `Optional<String> lang = languageDetector.detect(textObject);` gives an error "Type mismatch: cannot convert from Optional<LdLocale> to Optional<String>"

**Comment by fabiankessler** [comment]
Regarding readAllBuiltIn():
Thanks, I've updated the README.

About Optional:
The LanguageDetector interface uses the Optional from Guava: 
import com.google.common.base.Optional;
Your code probably uses the one from Java8 java.util.Optional. Can you confirm?

**Comment by KonradHoeffner** [comment]
Ah you are right, I could resolve the issue by changing the import to Guava Optional. But maybe refactoring to java.util.Optional would be better? As far as I see it, Guava Optional was only a stopgap measure when Java didn't support it so it is obsolete now.

**Comment by fabiankessler** [comment]
In my opinion it's way too early to require Java8. 
The library language-detector currently requires Java7 and I vote for keeping it this way for quite some time. 
Other libraries still support 6 or 5 to be widely usable.
My employer still runs many machines with JDK7. 
As far as I can tell, the latest Ubuntu LTS (14.04) has OpenJDK7 as the default.
Concluding: at some point in the future a change could be considered. Until then I'll close this task. 
Thanks for you input!
