### ISSUE TITLE
ShortText algorithm sometimes yields zero probabilities for all languages

### ISSUE THREAD

**Issue by AlbertWeichselbraun** [optimaize/language-detector#40]
`detectBlockShortText` does not break, once `CONV_THRESHOLD` has been reached. Depending on the text size this leads to zero probabilities for all languages.

### Example:

The bulgarian sentence
  `Европа не трябва да стартира нов конкурентен маратон и изход с приватизация`
yields a zero probability for all languages and, therefore, no result.

### How to reproduce:

add the following line to `runTests` in the `DataLanguageDetectorImplTest` unittest:
```java
assertEquals(detector.getProbabilities(text("Европа не трябва да стартира нов конкурентен маратон и изход с приватизация")).get(0).getLocale().getLanguage(), "bg");
```

**Comment by danielnaber** [comment]
It seems to me the `break` introduces a bug, please see #91.
