### ISSUE TITLE
need instructions on how to use/install

### ISSUE THREAD

**Issue by angelaqiu** [optimaize/language-detector#42]
Very unclear on how to use this library.... is there a jar file? Should I import the entire github project?

**Comment by rednoah** [comment]
Jar is on Maven Central. Download it yourself, or better yet, use Maven or Ivy for dependency management. Code samples in the README are more than sufficient.

**Comment by fabiankessler** [comment]
Yeah it's a bit tricky for fresh developers to get started with all those technologies. The Maven identifier is the first thing on the project's page. So anyone who has used that instantly knows what's to do. 

Here's the Maven Central page http://search.maven.org/#artifactdetails|com.optimaize.languagedetector|language-detector|0.5|jar where the Jar is linked.

As with other code libraries out there, a minimal knowledge is required.

**Comment by angelaqiu** [comment]
I'm getting an error for "languageDetector.detect(textObject);" -- it says "The type com.google.common.base.Optional cannot be resolved. It is indirectly referenced from required .class files." How do I fix this? The only thing it advises me to do is to fix the build path, but I have no other jars to add.....

**Comment by angelaqiu** [comment]
Never mind, I switched to getProbabilities() and fixed that problem, but now when I run it, it says "Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Splitter" which I've found seems to indicate that I'm missing a jar, but I have them included. What could be wrong?

**Comment by fabiankessler** [comment]
According to the messages you must be missing the Guava library. (Googling the class path of the mentioned classes Optional and Splitter shows that.)
