### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [optimaize/language-detector#67]
Hi

The following source files are without license headers:

./src/main/java/com/cybozu/labs/langdetect/util/Util.java
./src/main/java/com/cybozu/labs/langdetect/util/CharNormalizer.java
./src/main/java/com/optimaize/langdetect/LanguageDetector.java
./src/main/java/com/optimaize/langdetect/LanguageDetectorBuilder.java
./src/main/java/com/optimaize/langdetect/LanguageDetectorImpl.java
./src/main/java/com/optimaize/langdetect/NgramFrequencyData.java
./src/main/java/com/optimaize/langdetect/i18n/LdLocale.java
./src/main/java/com/optimaize/langdetect/ngram/BackwardsCompatibleNgramFilter.java
./src/main/java/com/optimaize/langdetect/ngram/NgramExtractor.java
./src/main/java/com/optimaize/langdetect/ngram/NgramExtractors.java
./src/main/java/com/optimaize/langdetect/ngram/NgramFilter.java
./src/main/java/com/optimaize/langdetect/ngram/OldNgramExtractor.java
./src/main/java/com/optimaize/langdetect/ngram/package-info.java
./src/main/java/com/optimaize/langdetect/ngram/StandardNgramFilter.java
./src/main/java/com/optimaize/langdetect/profiles/BuiltInLanguages.java
./src/main/java/com/optimaize/langdetect/profiles/LanguageProfile.java
./src/main/java/com/optimaize/langdetect/profiles/LanguageProfileBuilder.java
./src/main/java/com/optimaize/langdetect/profiles/LanguageProfileImpl.java
./src/main/java/com/optimaize/langdetect/profiles/LanguageProfileReader.java
./src/main/java/com/optimaize/langdetect/profiles/LanguageProfileWriter.java
./src/main/java/com/optimaize/langdetect/profiles/OldLangProfileConverter.java
./src/main/java/com/optimaize/langdetect/profiles/package-info.java
./src/main/java/com/optimaize/langdetect/profiles/util/LanguageLister.java
./src/main/java/com/optimaize/langdetect/text/CharNormalizerTextFilterImpl.java
./src/main/java/com/optimaize/langdetect/text/CommonTextObjectFactories.java
./src/main/java/com/optimaize/langdetect/text/MultiTextFilter.java
./src/main/java/com/optimaize/langdetect/text/package-info.java
./src/main/java/com/optimaize/langdetect/text/RemoveMinorityScriptsTextFilter.java
./src/main/java/com/optimaize/langdetect/text/UrlTextFilter.java
./src/main/java/com/optimaize/langdetect/text/TextFilter.java
./src/main/java/com/optimaize/langdetect/text/TextObject.java
./src/main/java/com/optimaize/langdetect/text/TextObjectFactory.java
./src/main/java/com/optimaize/langdetect/text/TextObjectFactoryBuilder.java

./src/test/java/be/frma/langguess/GenProfileTest.java
./src/test/java/com/cybozu/labs/langdetect/util/CharNormalizerTest.java
./src/test/java/com/optimaize/langdetect/DataLanguageDetectorImplTest.java
./src/test/java/com/optimaize/langdetect/LanguageDetectorImplTest.java
./src/test/java/com/optimaize/langdetect/i18n/LdLocaleTest.java
./src/test/java/com/optimaize/langdetect/ngram/BackwardsCompatibleNgramFilterTest.java
./src/test/java/com/optimaize/langdetect/ngram/NgramExtractorTest.java
./src/test/java/com/optimaize/langdetect/ngram/OldNgramExtractorTest.java
./src/test/java/com/optimaize/langdetect/ngram/StandardNgramFilterTest.java
./src/test/java/com/optimaize/langdetect/profiles/LanguageProfileBuilderTest.java
./src/test/java/com/optimaize/langdetect/profiles/LanguageProfileReaderTest.java
./src/test/java/com/optimaize/langdetect/profiles/LanguageProfileWriterTest.java
./src/test/java/com/optimaize/langdetect/text/MultiTextFilterTest.java
./src/test/java/com/optimaize/langdetect/text/RemoveMinorityScriptsTextFilterTest.java
./src/test/java/com/optimaize/langdetect/text/TextObjectTest.java

Please, confirm the licensing of code and/or content/s, and add license headers.

https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by fabiankessler** [comment]
Also, the license header is not present in the data files. And in the pom file. And in the readme. And in the license file. Oh, wait, never mind about that. I guess?

I confirm that the project's license is valid for all code contributed by me, and by my employer. Because the code is based on a fork, which again is based on a fork, you may want to check those sources.

A license header can be added to java files. Not to data files for obvious reasons. I would merge a pull request.
